# Generated by Django 5.2.4 on 2025-08-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address2',
            field=models.CharField(blank=True, max_length=239, null=True),
        ),
    ]
