# Generated by Django 5.2.4 on 2025-08-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sme_app', '0002_employee_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address2',
        ),
    ]
