# Generated by Django 5.2.4 on 2025-08-08 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme_app', '0003_remove_employee_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_code', models.CharField(max_length=50, unique=True)),
                ('operation', models.CharField(max_length=100)),
                ('mach', models.CharField(max_length=100)),
                ('smv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='efp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(default='EM-000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Daily_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user_efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sme_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_amounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sme_app.employee')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sme_app.styles')),
            ],
        ),
    ]
